"""仮

Revision ID: 55627e390a04
Revises: 22ca95e8b156
Create Date: 2025-08-01 10:01:28.507194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55627e390a04'
down_revision = '22ca95e8b156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_number', sa.Float(), nullable=True))

    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.drop_column('custom_number')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
