"""Remove main_group column

Revision ID: 81a48e804783
Revises: 332efe4918d6
Create Date: 2025-07-14 18:32:09.305961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a48e804783'
down_revision = '332efe4918d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('main_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_group', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
